
export const FETCH_POKEMONS_REQUEST = "FETCH_POKEMONS_REQUEST";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";
export const FETCH_POKEMON_DETAIL_REQUEST = "FETCH_POKEMON_DETAIL_REQUEST";
export const FETCH_POKEMON_DETAIL_SUCCESS = "FETCH_POKEMON_DETAIL_SUCCESS";
export const FETCH_POKEMON_DETAIL_FAILURE = "FETCH_POKEMON_DETAIL_FAILURE";